### ISSUE TITLE
Links to games?

### ISSUE THREAD

**Issue by RoelN** [iiyo/toothrot#3]
Hi there! This project looks super interesting, and I was wondering if there are any demos or example games you could link to. This really helps with understanding how Toothrot would look and feel during game play.

**Comment by jsteinbeck** [comment]
Hi Roel! Thank you!

I'm currently writing extensive documentation for the project and along with that will come example games as well. In the meantime, here's a version of the infamous Cloak of Darkness implemented in Toothrot:
https://games.toothrot.one/cloak-of-darkness/

You can take a look at the source code here:
https://raw.githubusercontent.com/toothrot-if/toothrot-examples/master/cloak-of-darkness/resources/story.trot.md

**Comment by RoelN** [comment]
Thanks for the links! I don't know if it's part of Toothrot, or part of the gameplay, but a few things stood out for me as a first time player:

- Isn't it a bit unusual that you can _sometimes_ click `cloak`, like when you're in the dark room, but not in other situations? Or is that because only now `cloak` is mentioned as part of the description?
- It wasn't obvious to me you could continue by clicking anywhere outside the text. E.g. when you're asked if you want to hang your cloak on the hook, it might be nice to have a `I'll keep my cloak on`, or just a simple `Continue`?
- Kinda the same issue: the three dots kinda look like a web loading "spinner", which had me thinking there was more coming but the page had to download/process something first. Maybe it could be made clearer that input is expected?

Just reporting this as a fellow developer, not complaining :-)

I like the fact that the text appears with the fade-in. I've always felt that text adventures could become so much more atmospheric with touches like that. Keep up the good work!

**Comment by jsteinbeck** [comment]
Thanks for sharing your impressions, Roel!

**Regarding your first point:** Links in Toothrot are comparable to those in Twine, that is they are really just linked text. There's no magic behind the nodes that inserts links automatically; in this regard it differs quite drastically from most parser-based text adventures, where the game always responds to certain keywords if an object is present in the room. Therefore, in Toothrot it's the game developers decision which words should be links in what circumstances.

**Regarding your second and third point:** I got the same feedback from someone else about clicking on the screen and the dots. I kinda agree with that impression, but I'm not really sure yet what to do about it.

One idea was to always have a first node that tells the player that they can click anywhere when the dots appear. I know of some mobile IF (published by Cornelsen I think) that does something similar: When you first start the game, there's a text saying something like "Tap to start the game", thus making the player aware that this is a possibility. I'm a little wary though about forcing that decision (starting with a notice) on every game developer by making it mandatory -- so I tend to think that if a game developer wanst to display that kind of notice at the start, they can just write it themselves.

Maybe it would help to have three different kinds of indicators: 

* The dots could remain for those nodes that have an "autonext", that is when the story continues even without player interaction
* An arrow to the right (with a pointer cursor on hover) would indicate that there's a next node
* An arrow to the left (also changing the cursor on hover) would indicate that clicking returns the player to a previous node

If you have any other ideas, please let me know!

**Comment by jsteinbeck** [comment]
FYI, I implemented the idea with separate indicators and you can see the updated Cloak of Darkness here:
https://games.toothrot.one/cloak-of-darkness/ (You might need to reload twice because of AppCache)

The old behavior can still be used by setting the settings `useReturnIndicator` and `useNextIndicator` to `false`. Also, if `useReturnIndicator` is `false` but `useNextIndicator` is `true`, the next indicator will be used for returns as well.

**Comment by RoelN** [comment]
Thanks for taking the time to explain! I checked out the updated version. I think the "loading dots" are a bit distracting, and not really necessary: you get visual feedback from the appearing text, and there's always the button to the next node.

I wonder if a simple, full width button with a ▼ would do the trick? It'll be the universal option to advance in the story (either revealing new text, or being the "continue without any of the given options"). It matches the direction of the story, and I think it's a pretty well established indicator in regular video games.

Something like this: https://codepen.io/RoelN/pen/eyMJXZ

(Uncomment the other button in the HTML to see how it could work with other options than "Continue")

**Comment by jsteinbeck** [comment]
Thanks again for the suggestions and taking the time to make a codepen, Roel!

I'm pondering whether to make the indicator look like an actual full-width button, maybe that makes things even clearer. And changing the default indicator triangle to a downwards-facing one might be a good idea, too. I'll play around with the different options a bit to see which one feels most natural.

What I do think though, in any case, is that the indicators should look different than the option buttons because the semantics behind them are quite different as well. I've seen many ChoiceScript and Twine games have an arbitrarily-named "next" or "back" option/link and to me personally that always feels like a crutch that's only used because the engine doesn't offer anything more fitting for this particular usecase.

As for your suggestion about getting rid of the dots indicator: I do think it is quite handy. When the dots are displayed, it means that the next text node will appear automatically, and the *next indicator* (right-facing triangle) isn't always visible either, because a node can have a so-called  `autonextTarget` instead of having a `next` node.

Having the `autonext` (dots) indicator is useful for Lifeline-style games, and the dots are a genre-neutral way of indicating something's happening "in the background". If one wants to customize it, they can do that rather easily by chaning a template and/or the CSS for the indicator. For example, you could change the appearance of the indicator to `Emily is typing...` or something along those lines.

I might add a setting to disable the `autonext` indicator though.

**Comment by RoelN** [comment]
Ah, yes, some puzzle pieces just fell into place, thanks for the explanation!

So the dots are a way to say "there's more text coming up automatically if you wait for it, but you could also tap the button to see it now". I agree that giving no feedback at all would be confusing. You wouldn't know if anything else was coming, if input is expected, etc.

Maybe I'm inspired by the fade-in style the text show now, which makes the text look like it's typed in — it appears letter by letter — that I think a flashing cursors could be a nice visual cue. It sort of says "the other end is not finished typing yet". But it might be too computer-y for some stories. 

Anyway, I'll be keeping an eye on the project and I'm looking forward to playing some games with it!
